// <auto-generated />
using System;
using ButcePlanlayicisiWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ButcePlanlayicisiWeb.Migrations
{
    [DbContext(typeof(ButceDbContext))]
    [Migration("20260815122828_IlkVeritabani")]
    partial class IlkVeritabani
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ButcePlanlayicisiWeb.Models.ButceKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gelir")
                        .HasColumnType("REAL");

                    b.Property<double>("Gider")
                        .HasColumnType("REAL");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ButceKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
